name: Deploy to Heroku

on: [push]

jobs:
  # install_docker:
  #   name: Install Docker CE
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Docker repository
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install \
  #           apt-transport-https \
  #           ca-certificates \
  #           curl \
  #           gnupg-agent \
  #           software-properties-common
  #         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #         sudo apt-key fingerprint 0EBFCD88
  #         sudo add-apt-repository \
  #           "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  #           $(lsb_release -cs) \
  #           stable"
  #     - name: Install Docker CE
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install docker-ce docker-ce-cli containerd.io
  #         sudo docker run hello-world
  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        run: docker image build -t $HEROKU_APP .
        env:
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
      - name: Login to Heroku
        uses: actions/heroku@master
        with:
          args: container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
      - name: Push image to Heroku
        uses: actions/heroku@master
        with:
          args: container:push worker --arg GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY}},DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      - name: Release image to Heroku dyno
        uses: actions/heroku@master
        with:
          args: container:release worker
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
      # - name: Set environment variables
      #   uses: actions/heroku@master
      #   with:
      #     args: config:set GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY}} DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #     HEROKU_APP: ${{ secrets.HEROKU_APP }}
      #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      #     DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      - name: Run image in Heroku dyno
        uses: actions/heroku@master
        with:
          args: container:run worker -a $HEROKU_APP
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
      # - name: Run image in Heroku dyno
      #   uses: actions/heroku@master
      #   with:
      #     args: run:worker docker run -e $GOOGLE_API_KEY -e $DISCORD_TOKEN node .
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #     HEROKU_APP: ${{ secrets.HEROKU_APP }}
      #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      #     DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}